# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- hosts: primary
  tasks:
    - name: "set default gate scripts"
      set_fact:
        gate_scripts_default:
          - ./tools/deployment/01_install_kubectl.sh
          - ./tools/deployment/02_install_clusterctl.sh
          - ./tools/deployment/21_systemwide_executable.sh
          - ./tools/deployment/22_test_configs.sh
          - ./tools/deployment/23_pull_documents.sh
          - ./tools/deployment/24_build_ephemeral_iso.sh
          - ./tools/deployment/25_deploy_ephemeral_node.sh
          - ./tools/deployment/26_deploy_metal3_capi_ephemeral_node.sh
          - ./tools/deployment/30_deploy_controlplane.sh
          - ./tools/deployment/31_deploy_initinfra_target_node.sh
          - ./tools/deployment/32_cluster_init_target_node.sh
          - ./tools/deployment/33_cluster_move_target_node.sh
          - ./tools/deployment/34_deploy_worker_node.sh

    - name: "Run gate scripts"
      shell: |
        set -xe;
        # NOTE(drewwalters96): Rather than re-cloning airshipctl, this uses the
        # airshipctl repo cloned to the disk by Zuul.
        export AIRSHIP_CONFIG_PRIMARY_REPO_URL={{ airshipctl_path | quote }}
        export AIRSHIP_CONFIG_METADATA_PATH={{ metadata_path | quote }}
        export AIRSHIPCTL_PATH={{ airshipctl_path | quote }}
        export OSH_DEPLOYMENTS_PATH={{ osh_deployments_path | quote }}
        {{ gate_script_path }}
      args:
        chdir: "{{ zuul.projects['opendev.org/airship/airshipctl'].src_dir }}"
      vars:
        airshipctl_path: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/airship/airshipctl'].src_dir }}"
        gate_script_path: "{{ item }}"
        metadata_path: "openstack-helm-deployments/manifests/site/test-site/metadata.yaml"
        osh_deployments_path: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
      with_items: "{{ gate_scripts | default(gate_scripts_default) }}"
